services:
  - type: web
    name: welldiary
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: welldiary-db
          property: connectionString
    autoDeploy: false

databases:
  - name: welldiary-db
    databaseName: welldiary
    user: welldiary